name: UK-FT-UBI
dependencies:
- python
- plotly
- pandas
- numpy
- pip
- pip:
  - jupyter-book
  - ipywidgets
  - rdbl
  - "git+https://github.com/nikhilwoodruff/openfisca-uk.git"
  - "git+https://github.com/PSLmodels/microdf.git"